%YAML 1.1
---
name: AaronLasseigne.com
url: https://aaronlasseigne.com
description: Freelance coder. Avid scholar. Amateur educator.
highlighter: rouge
timezone: Etc/UTC
encoding: utf-8
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/posts/page:num"
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - node_modules

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"
