%YAML 1.1
---
name: AaronLasseigne.com
url: http://aaronlasseigne.com
description: Codewright (mostly Ruby), gin drinker, football watcher, husband and father.
highlighter: pygments
timezone: Etc/UTC
encoding: UTF-8
excerpt_separator: <!--more-->
paginate: 5
permalink: pretty

exclude:
  - CNAME
  - fontello-config.json
  - cogs.json
  - package.json
  - Makefile
  - css

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "default"
